language: python
python:
  - "3.6"
script:
  - pelican content
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  local-dir: output
  on:
    branch: master